service: stateflow
provider:
  name: aws
  region: eu-west-1
  runtime: python3.8
  iam:
    role: arn:aws:iam::958167380706:role/stateflow-dev-eu-west-1-lambdaRole
plugins:
  - serverless-python-requirements
package:
  exclude:
    - 'venv/**'
custom:
  pythonRequirements:
    usePipenv: false
    slim: true
    noDeploy:
      - Flask
      - flake8
      - apache-beam
      - coverage
      - confluent-kafka
      - beam-nuggets
      - httplib2
      - google-api-python-client
      - pytest-mock
      - PyHamcrest
      - pytest-docker-fixtures
      - pytest-timeout
      - apache-flink
      - boto3
functions:
  stateflow:
    handler: aws_runtime_gateway.handler
    memorySize: 1024 # optional, in MB, default is 1024